"""Views, one for each Insta485 page."""
from insta485.views.index import show_index
from insta485.views.index import show_explore
from insta485.views.account import show_login
from insta485.views.account import accounts
from insta485.views.account import insert_image
from insta485.views.account import log_out
from insta485.views.account import show_edit
from insta485.views.account import show_user
from insta485.views.account import show_password
from insta485.views.account import show_create
from insta485.views.account import show_delete
from insta485.views.account import show_followers
from insta485.views.account import show_following
from insta485.views.account import following
from insta485.views.posts import show_post
from insta485.views.posts import likes
from insta485.views.posts import comments
from insta485.views.posts import posts
